apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nifi-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  # - port:
  #     number: 80
  #     name: http
  #     protocol: HTTP
  #   hosts:
  #   - nifi.tmanet.com
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gw-credential
    hosts:
    - nifi.tmanet.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nifi-vs
spec:
  gateways:
  - nifi-gateway
  hosts:
  - nifi.tmanet.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: simplenifi.nifi.svc.cluster.local
        port:
          number: 8080
