apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: simplenifi
spec:
  service:
    headlessEnabled: true
    labels:
      cluster-name: simplenifi
  pod:
    annotations:
      sidecar.istio.io/inject: "false"
  zkAddress: "zookeeper:2181"
  zkPath: /simplenifi
  externalServices:
    - metadata:
        labels:
          cluster-name: simplenifi
      name: simplenifi
      spec:
        portConfigs:
          - internalListenerName: https
            port: 8443
        type: ClusterIP
  sidecarConfigs:
    - name: app-log
      image: "busybox:1.32.0"
      args: [ tail, -n+1, -F, /var/log/nifi-app.log ]
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - name: logs
          mountPath: /var/log
    - name: bootstrap-log
      image: "busybox:1.32.0"
      args: [tail, -n+1, -F, /var/log/nifi-bootstrap.log]
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - name: logs
          mountPath: /var/log
    - name: user-log
      image: "busybox:1.32.0"
      args: [tail, -n+1, -F, /var/log/nifi-user.log]
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - name: logs
          mountPath: /var/log
  clusterImage: "apache/nifi:1.26.0"
  initContainerImage: "bash:5.2.2"
  oneNifiNodePerNode: false
  readOnlyConfig:
    nifiProperties:
      webProxyHosts:
        - nifi.tmanet.com:8443
      overrideConfigs: |
        nifi.sensitive.props.key=thisIsABadSensitiveKeyPassword
  pod:
    labels:
      cluster-name: simplenifi
  nodeConfigGroups:
    default_group:
      imagePullPolicy: IfNotPresent
      isNode: true
      serviceAccountName: default
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          reclaimPolicy: Delete
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "default"
            resources:
              requests:
                storage: 10Gi
      resourcesRequirements:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - containerPort: 8443
        type: https
        name: https
      - containerPort: 6007
        type: cluster
        name: cluster
      - containerPort: 10000
        type: s2s
        name: s2s
      - containerPort: 9090
        type: prometheus
        name: prometheus
      - containerPort: 6342
        type: load-balance
        name: load-balance
    sslSecrets:
      tlsSecretName: "simplenifi-tls-secret"
      create: true
      issuerRef:
        name: nifi-issuer
        kind: Issuer
